[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai" # Memecore evm version is shanghai. 
solc_version = "0.8.24"  # You can use the other version, but we recommend 0.8.24 because its default EVM version is shanghai.
etherscan_api_key = "1234" # Dummy value used to bypass Blockscout verification errors when using forge. 
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
insectarium = "https://rpc.insectarium.memecore.net"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options